{{- if .Values.karpenter.enabled -}}
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ .Release.Name }}-karpenter-ec2nodeclass
spec:
  amiFamily: {{ .Values.karpenter.ec2NodeClass.amiFamily }}
  subnetSelectorTerms: {{- toYaml .Values.karpenter.ec2NodeClass.subnetSelectorTerms | nindent 4}}
  securityGroupSelectorTerms: {{- toYaml .Values.karpenter.ec2NodeClass.securityGroupSelectorTerms | nindent 4}}
  role: {{ .Values.karpenter.ec2NodeClass.role }}
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: {{ .Release.Name }}-karpenter-nodepool
spec:
  template:
    metadata:
      labels:
        type: karpenter
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: {{ .Release.Name }}-karpenter-ec2nodeclass
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: {{ .Values.karpenter.nodePool.requirements.arch | toJson }}
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: {{ .Values.karpenter.nodePool.requirements.capacityTypes | toJson }}
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: {{ .Values.karpenter.nodePool.requirements.instanceTypes | toJson }}
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: {{ .Values.karpenter.nodePool.requirements.zones | toJson }}
  limits:
    cpu: {{ .Values.karpenter.nodePool.limits.cpu }}
    memory: {{ .Values.karpenter.nodePool.limits.memory }}
{{- end }}
